clowder/cmd.py, clowder/model/clowder_repo.py, clowder/model/clowder_yaml.py, clowder/model/group.py, clowder/model/project.py, clowder/utility/git_utilities.py, clowder/utility/print_utilities.py, scripts/test_cats_example.sh, scripts/test_llvm_projects_example.sh, setup.py
Selectively print group and project status when running `clowder groom` and `clowder stash` commands
=> Further output formatting

clowder/model/clowder_yaml.py, clowder/utility/git_utilities.py
=> yaml validation

clowder/model/clowder_yaml.py, clowder/model/group.py, clowder/model/project.py
Only run `forall` command once per directory, now that more than one project can reference the same directory.
=> Fix `forall` functionality

clowder/cmd.py, clowder/model/clowder_yaml.py, clowder/model/project.py, clowder/utility/git_utilities.py, clowder/utility/print_utilities.py, scripts/test_cats_example.sh, scripts/test_llvm_projects_example.sh, scripts/test_srclib_example.sh, setup.py
=> Add more error tests to Travis CI scripts

clowder/clowder_repo.py, clowder/project.py, clowder/utility/clowder_utilities.py, clowder/utility/git_utilities.py, clowder/utility/print_utilities.py
Move functions that don't rely on GitPython to a separate file. Fix logic for checking out branches, sha's, and tags.
=> Refactor git utilities

clowder/clowder_yaml.py, clowder/group.py
Use list comprehensions where possible
=> List comprehensions

README.md, clowder/clowder_yaml.py, clowder/cmd.py, scripts/test_cats_example.sh, scripts/test_llvm_projects_example.sh, scripts/test_srclib_example.sh, setup.py
Combine `forall` and `forall_groups` methods
=> Consolidate group methods

clowder/clowder_repo.py, clowder/clowder_yaml.py, clowder/cmd.py, clowder/utility/clowder_utilities.py, clowder/utility/git_utilities.py, scripts/test_cats_example.sh, setup.py
=> Test missing groups

README.md, clowder/clowder_yaml.py, scripts/test_cats_example.sh
=> Validate version name

README.md, clowder/cmd.py, scripts/test_cats_example.sh, scripts/test_llvm_projects_example.sh, scripts/test_srclib_example.sh, setup.py
Change `forall` command argument from optional to positional
=> Forall command argument

clowder/clowder_yaml.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_utilities.py, setup.py
Print individual status messages for missing projects
=> Better messaging for checking project existince with `clowder fix`

README.md, scripts/tests/cats_example.sh, scripts/tests/functional_tests.sh, scripts/tests/llvm_projects_example.sh, scripts/tests/srclib_example.sh
Use utility functions for more modular examples test scripts
=> Refactor test scripts

README.md, clowder/clowder_yaml.py, clowder/cmd.py, clowder/group.py, scripts/tests/cats_example.sh, scripts/tests/functional_tests.sh, scripts/tests/llvm_projects_example.sh, scripts/tests/srclib_example.sh
Add `-p`/`--projects` option for specifying specific projects in commands
=> Add -p/--projects option

scripts/tests/cats_example.sh
Add tests to cats_example.sh test script for case when there are no fixed versions.
=> Add tests for no fixed versions

setup.py
=> Release v0.7.0

clowder/project.py, clowder/utility/git_utilities.py, scripts/test_cats_example.sh, scripts/test_llvm_projects_example.sh, scripts/test_srclib_example.sh, scripts/test_utilities.sh, scripts/unittests.sh, setup.py, test/test_git_utilities.py
Test for missing directories when using the `clowder groom` and `clowder stash` commands.
=> Add tests for missing directories

README.md, clowder/utility/git_utilities.py, setup.py
Add exception handling when initializing `Repo` instances
=> Repo instance init exception handling

clowder/clowder_repo.py, clowder/utility/clowder_utilities.py, setup.py, uninstall.sh
Move symlink creation to a separate function
=> Force symlink

clowder/utility/git_utilities.py
Change "correct" to "default" for message when on branch specified in `clowder.yaml`
=> Better message

clowder/utility/git_utilities.py
=> Add log message when fetching new data

README.md
Add CircleCI status badge to `README.md`
=> CircleCI status badge

clowder/utility/git_utilities.py
=> Failure message formatting

clowder/cmd.py
Check for None on args. Fxs issue #77
=> simple check for none

.gitignore, README.md, clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, examples/cats/clean.sh, examples/llvm-projects/clean.sh, examples/srclib/clean.sh, scripts/test_cats_example.sh, scripts/test_utilities.sh, setup.py, test/test_clowder_repo.py
=> Update clowder repo path to use dot prefix

clowder/cmd.py
=> Fix herd twice bug

scripts/deploy.sh, setup.py
Remove `v` prefix from tags. Release 0.8.1
=> Update deploy tag

README.md, setup.py
Release new version with updated message output and removal of `clowder sync` command.
=> Version 0.8.2

clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/group.py, scripts/deploy.sh, scripts/test_cats_example.sh, scripts/test_llvm_example.sh, scripts/test_srclib_example.sh, scripts/test_utilities.sh, scripts/unittests.sh
=> Add clowder --version option

install.sh, uninstall.sh, update_version.sh
=> Add update_version script

.travis.yml, README.md, clowder/clowder_controller.py, clowder/project.py, clowder/utility/git_utilities.py, scripts/test_llvm_example.sh, test/shared.py, test/test_group.py, test/test_project.py
closes #99 
Also adds more concise handling of yaml defaults
=> Add depth option to clowder.yaml

README.md, clowder/clowder_controller.py, clowder/fork.py, clowder/project.py, clowder/utility/clowder_utilities.py, test/test_group.py, test/test_project.py
=> Add proper support for forks

clowder/clowder_repo.py, clowder/fork.py, clowder/project.py, clowder/utility/git_utilities.py
- Fetch specific remotes
- Fetch specific refs
=> Depth enhancements

.travis.yml, clowder/utility/clowder_utilities.py, scripts/test_cats_example.sh, scripts/test_srclib_example.sh
- Print messages indicating error in yaml file
- Add missing validation functionality
- Refactor
=> yaml validation enhancements

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/git_utilities.py, docs/commands.md, scripts/test_cats_example.sh, scripts/test_llvm_example.sh
=> Add `clowder start` command

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/git_utilities.py, docs/commands.md, scripts/test_cats_example.sh
=> Add `clowder prune` command

README.md, clowder/clowder_repo.py, clowder/cmd.py, docs/commands.md, examples/cats/init.sh, scripts/test_cats_example.sh
=> Add --branch\-b option to `clowder init`

.travis.yml, README.md, clowder/clowder_repo.py, clowder/cmd.py, clowder/project.py, clowder/utility/git_utilities.py, docs/commands.md, scripts/test_cats_example.sh, scripts/test_utilities.sh, scripts/unittests.sh, setup.py, test/test_clowder_repo.py, test/test_git_utilities.py, test/test_project.py
=> Add `clowder repo` subcommands

clowder/utility/clowder_utilities.py, scripts/test_cats_example.sh, scripts/test_llvm_example.sh, scripts/test_srclib_example.sh, scripts/test_utilities.sh, scripts/unittests.sh
=> Update test scripts

README.md, clowder/cmd.py, scripts/test_utilities.sh, test/test_fork.py
=> Add unit tests for the fork class

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, docs/commands.md, scripts/test_cats_example.sh, scripts/test_llvm_example.sh
Adds option to specify branch to herd on the command line
=> Add `clowder herd -b` command option

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/fork.py, clowder/group.py, clowder/project.py, docs/commands.md, scripts/deploy.sh, test/test_fork.py
Adds `-d`/`--depth` option for `clowder herd` on command line
=> Add command line depth option for herd command

README.md, clowder/clowder_repo.py, clowder/cmd.py, clowder/utility/clowder_utilities.py, docs/commands.md, scripts/test_cats_example.sh, scripts/test_utilities.sh, setup.py, test/test_clowder_repo.py
resolves #141 
and
resolves #139
=> Add `clowder link` command

LICENSE, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/git_utilities.py, docs/commands.md
=> Prune remote branches

clowder/clowder_controller.py, clowder/cmd.py, clowder/project.py, docs/commands.md, script/test_forall_script.sh, script/test_utilities.sh
=> Add ability to run scripts with `clowder forall`

clowder/utility/clowder_utilities.py, clowder/utility/git_utilities.py
=> Print number of new local and upstream commits

clowder/clowder_repo.py, clowder/utility/git_utilities.py
=> Always fetch clowder repo before printing status

clowder/utility/git_utilities.py, examples/cats/clean.sh, examples/fastlane/clean.sh, examples/llvm-projects/clean.sh, examples/srclib/clean.sh, script/clean, script/deploy, script/test, script/test_cats_example.sh, script/test_llvm_example.sh, script/test_utilities.sh, script/unittests.sh, script/update
Fixes issue with running `test_forall_script.sh` with `clowder forall -f`
=> Update test scripts with new method for determining directory location

clowder/clowder_repo.py, clowder/cmd.py, clowder/project.py, clowder/utility/git_utilities.py
Standardize output grammar and update coloring for better portability
=> Output formatting tweaks

clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, docs/commands.md, script/test_utilities.sh
=> Add `-f` option to `clowder status`

clowder/clowder_repo.py, clowder/project.py, clowder/utility/clowder_utilities.py
=> Tweak project status output formatting

clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/utility/repeated_timer.py, script/test_llvm_example.sh, script/test_utilities.sh
=> Print status indicator while fetching

clowder/clowder_controller.py
=> Remove dotfiles from versions

clowder/clowder_repo.py, script/setup
=> Remove .clowder directory if `clowder init` fails

clowder/clowder_controller.py, clowder/cmd.py, clowder/project.py, docs/commands.md, script/test_forall_script_error.sh, script/test_utilities.sh
=> Add --ignore-errors option to `clowder forall`

README.md, clowder/cmd.py, docs/commands.md, script/test_cats_example.sh, script/test_llvm_example.sh
Will be added back later once the logic is better worked out
=> Remove `clowder herd -b` option

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/git_utilities.py, docs/commands.md, script/test_cats_example.sh
=> Add --force/-f option to `clowder prune`

clowder/clowder_controller.py, clowder/cmd.py, clowder/project.py, docs/commands.md, script/test_utilities.sh
Remove `clowder forall -f` option
=> Consolidate `clowder forall -c` to run command or script

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/git_utilities.py, docs/commands.md, script/clean, script/test_cats_example.sh, script/test_llvm_example.sh, script/test_utilities.sh
=> Add `--tracking,-t` to`clowder start` and create related tests

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/git_utilities.py, docs/commands.md, script/test_cats_example.sh
=> Add `--all/-a` option to `clowder prune`

README.md, clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/fork.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_utilities.py, clowder/utility/clowder_yaml_validation.py, clowder/utility/git_utilities.py, script/test_cats_example.sh, script/test_utilities.sh
=> Update formatting for `clowder prune` output

script/clean, script/test_cats_example.sh, script/test_llvm_example.sh, script/test_utilities.sh
=> Use hidden home directory for locally running tests

clowder/cmd.py, clowder/project.py, clowder/utility/git_print_utilities.py, clowder/utility/git_utilities.py, test/test_git_utilities.py
=> Use short git sha for output

clowder/clowder_controller.py, clowder/project.py, clowder/utility/clowder_yaml_validation.py, clowder/utility/print_utilities.py, script/test_cats_example.sh, script/test_utilities.sh, test/test_group.py, test/test_project.py
=> Update yaml validation tests

clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_utilities.py, clowder/utility/clowder_yaml_validation.py, clowder/utility/git_utilities.py, clowder/utility/print_utilities.py, docs/commands.md, script/test_cats_example.sh, script/test_utilities.sh
Change to use `subprocess.call()` instead of `Popen` for executing commands in order to preserve output formatting
resolves #215
=> Add `clowder diff` command

clowder/clowder_repo.py, clowder/cmd.py, clowder/utility/clowder_utilities.py, clowder/utility/git_utilities.py, clowder/utility/git_utilities_private.py, script/tests/test_cats_herd.sh
=> Add more `clowder herd` tests

clowder/clowder_repo.py, clowder/project.py
Only show project path in most output. Tweak .clowder output.
=> Update output formatting

clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/fork.py, clowder/project.py, clowder/utility/git_utilities.py, clowder/utility/git_utilities_private.py, docs/commands.md, script/tests/test_cats_herd.sh
=> Add `clowder herd -b`

clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/utility/git_print_utilities.py
=> Print diff when attempting to run command with dirty repo

clowder/project.py, clowder/utility/clowder_utilities.py, docs/commands.md, script/tests/test_cats_forall.sh, script/tests/test_forall_script_env_duke.sh, script/tests/test_forall_script_env_kit.sh
=> Add environment variables to `clowder forall`

script/tests/test_cats_repo.sh, script/tests/test_utilities.sh
=> Add tests for all `clowder repo` subcommands

README.md, clowder/clowder_controller.py, clowder/utility/clowder_yaml_loading.py, clowder/utility/clowder_yaml_validation.py, docs/clowder-yaml.md, script/README.md, script/tests/test_cats_import.sh
=> Import tests

clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_subparsers.py, clowder/utility/git_print_utilities.py, clowder/utility/git_utilities.py, docs/commands.md, script/tests/test_example_llvm.sh
=> Add `clowder sync` command

README.md, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_subparsers.py, clowder/utility/git_utilities.py, docs/commands.md, script/tests/test_cats_branch.sh, script/tests/test_example_cats.sh, script/tests/test_example_llvm.sh, script/tests/test_help.sh
=> Add `clowder branch` command

.gitignore, .travis.yml, examples/README.md, examples/swift-projects/README.md, examples/swift-projects/clean.sh, examples/swift-projects/init.sh, script/test, script/tests/test_example_swift.sh, script/tests/test_utilities.sh
=> Add Swift example

clowder/project.py, clowder/utility/git_utilities.py, clowder/utility/print_utilities.py, script/clean, script/tests/test_example_llvm.sh, script/tests/test_example_swift.sh, script/tests/test_utilities.sh
=> Rename remotes for pre-existing remotes

clowder/group.py, clowder/project.py, clowder/utility/clowder_yaml_loading.py, clowder/utility/clowder_yaml_validation.py, script/tests/test_cats_herd.sh, script/tests/test_utilities.sh, test/test_project.py
=> Add group clowder options

clowder/utility/clowder_yaml_loading.py, clowder/utility/clowder_yaml_validation.py, script/tests/test_cats_import.sh, script/tests/test_cats_offline.sh
=> Allow groups with projects in clowder.yaml with import

clowder/clowder_repo.py, clowder/cmd.py, clowder/utility/clowder_subparsers.py, clowder/utility/clowder_yaml_printing.py, docs/commands.md, script/tests/test_cats_repo.sh, script/tests/test_help.sh
=> Add command to print clowder.yaml file(s)

clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_subparsers.py, clowder/utility/clowder_utilities.py, clowder/utility/clowder_yaml_printing.py, docs/commands.md, script/tests/test_cats_repo.sh, script/tests/test_cats_yaml.sh, script/tests/test_example_cats.sh, script/tests/test_help.sh, test/test_group.py, test/test_project.py
=> Print resolved `clowder.yaml`

clowder/utility/clowder_yaml_loading.py, clowder/utility/clowder_yaml_validation.py, script/tests/test_example_swift.sh
=> Override project fork

script/tests/test_example_swift.sh, script/tests/test_swift_config_versions.sh
=> Add Swift config tests

.travis.yml, clowder/utility/clowder_utilities.py, clowder/utility/clowder_yaml_validation.py, clowder/utility/print_utilities.py, script/tests/test_swift_config_versions.sh
=> Validate ref format

clowder/project.py, clowder/utility/git_utilities.py, script/tests/test_cats_clean.sh, script/tests/test_utilities.sh
=> Abort rebase in `clowder clean`

clowder/project.py, clowder/utility/git_print_utilities.py, clowder/utility/git_utilities.py, script/tests/test_cats_clean.sh, script/tests/test_utilities.sh
=> Handle untracked files

clowder/clowder_repo.py, clowder/project.py, clowder/utility/git_print_utilities.py, clowder/utility/git_utilities.py, script/tests/test_cats_clean.sh, script/tests/test_example_cocos2d.sh, script/tests/test_utilities.sh
=> Clean submodules

clowder/project.py, clowder/utility/print_utilities.py
=> Handle case when fork and project have some remote name

clowder/clowder_controller.py, clowder/group.py, clowder/project.py, clowder/utility/git_utilities.py
=> Always clean even when not dirty

clowder/utility/git_utilities.py, clowder/utility/git_utilities_private.py
=> Prevent double fetch in `clowder herd -b`

script/test, script/tests/test_cats_offline.sh, script/tests/test_cats_prune.sh, script/tests/test_cats_repo.sh, script/tests/test_cats_start.sh, script/tests/test_example_cats.sh, script/tests/test_example_llvm.sh, script/tests/test_example_swift.sh
=> Update test scripts for better offline and write access handling

.idea/clowder.iml, .idea/misc.xml, clowder/clowder_controller.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_subparsers.py, clowder/utility/git_submodule_utilities.py, clowder/utility/git_utilities.py, clowder/utility/print_utilities.py, docs/commands.md, script/tests/test_cats_herd.sh, script/tests/test_example_cats.sh, script/tests/test_example_llvm.sh, script/tests/test_utilities.sh
=> Add rebase option

.pylintrc, clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_utilities.py, clowder/utility/clowder_yaml_printing.py, clowder/utility/clowder_yaml_validation.py, clowder/utility/git_submodule_utilities.py, clowder/utility/git_utilities.py
Refactor some areas of the code to be more pythonic, remove pylint disables and fix lint warnings.
=> Clowder refactor

.idea/clowder.iml, .idea/inspectionProfiles/Project_Default.xml, .idea/misc.xml, .pylintrc, clowder/clowder_controller.py, clowder/clowder_repo.py, clowder/cmd.py, clowder/group.py, clowder/project.py, clowder/utility/clowder_subparsers.py, clowder/utility/clowder_utilities.py, clowder/utility/clowder_yaml_loading.py, clowder/utility/clowder_yaml_printing.py, clowder/utility/clowder_yaml_validation.py, clowder/utility/git_submodule_utilities.py, clowder/utility/git_utilities.py, docs/commands.md, test/clowder_test/cmd.py, test/scripts/test_cats_herd_tag.sh, test/scripts/test_example_cats.sh, test/scripts/test_utilities.sh
=> Add `clowder herd -t` option

clowder/clowder/model/project.py
- Fixes output display bug for parallel commands
- Fix project double print bug
=> Fix bug in parallel output

README.md, clowder/clowder/clowder_controller.py, docs/README.md, docs/swift-update-checkout-config-json.md, docs/swift-update-checkout-py.md, docs/swift-update.md, examples/swift-projects/init.sh, test/scripts/swift/configure_remotes.sh, test/scripts/swift/write_configure_remotes.sh
resolves #289
resolves #349
- Add docs comparing `clowder` to Swift's `update_checkout.py` script
- Add various badges
=> Update Swift update_checkout docs and add bages

clowder/clowder/clowder_controller.py, clowder/clowder/cmd.py, clowder/clowder/util/formatting.py, test/scripts/cats/save.sh
resolves #348
- Disallows saving a version named `default`
=> Disallow saving a version named "default"

.idea/clowder.iml
- Fixes PyCharm project settings so that all files are shown in the editor
=> Update PyCharm project settings

.codeclimate.yml, clowder/clowder/clowder_controller.py, clowder/clowder/clowder_repo.py, clowder/clowder/cmd.py, clowder/clowder/error/clowder_error.py, clowder/clowder/error/clowder_git_error.py, clowder/clowder/git/project_repo.py, clowder/clowder/git/project_repo_recursive.py, clowder/clowder/git/repo.py, clowder/clowder/model/fork.py, clowder/clowder/model/group.py, clowder/clowder/model/project.py, clowder/clowder/model/source.py, clowder/clowder/util/clowder_yaml.py, clowder/clowder/util/connectivity.py, clowder/clowder/util/decorators.py, clowder/clowder/util/execute.py, clowder/clowder/util/file_system.py, clowder/clowder/util/formatting.py, clowder/clowder/util/progress.py, clowder/clowder/util/subparsers.py
- Adds more detailed Sphinx doc comments
=> Update sphinx documentation

.codeclimate.yml, .pylintrc, clowder/clowder/clowder_controller.py, clowder/clowder/clowder_repo.py, clowder/clowder/cmd.py, clowder/clowder/error/clowder_git_error.py, clowder/clowder/git/project_repo.py, clowder/clowder/git/project_repo_recursive.py, clowder/clowder/git/repo.py, clowder/clowder/model/fork.py, clowder/clowder/model/group.py, clowder/clowder/model/project.py, clowder/clowder/model/source.py, clowder/clowder/util/decorators.py, clowder/clowder/util/execute.py, clowder/clowder/util/formatting.py, docs/conf.py, setup.cfg, test/unittests/test_fork.py
- Use `**kwargs` to reduce number of parameters in methods
=> Refactor kwargs

README.md, clowder/clowder/clowder_controller.py, clowder/clowder/cmd.py, clowder/clowder/git/repo.py, clowder/clowder/model/project.py, clowder/clowder/util/decorators.py, clowder/clowder/util/subparsers.py, clowder_test/clowder_test/cmd.py, docs/commands.md, test/scripts/cats/checkout.sh, test/scripts/cats/offline.sh, test/scripts/test_example_cats.sh
resolves #268
- Add `clowder checkout` command to checkout branches using normal `git` logic
=> Add `clowder checkout` command

.idea/clowder.iml, clowder/clowder/clowder_controller.py, clowder/clowder/clowder_repo.py, clowder/clowder/model/defaults.py, clowder/clowder/model/fork.py, clowder/clowder/model/group.py, clowder/clowder/model/project.py, docs/clowder.error.rst, docs/clowder.git.rst, docs/clowder.model.rst, docs/clowder.util.rst, docs/general_documentation.rst, docs/plugins.md, examples/README.md, examples/plugins/README.md, examples/plugins/plugins.d/exampleplugin.conf, examples/plugins/plugins/exampleplugin.py, script/test, test/unittests/test_group.py, test/unittests/test_project.py
resolves #355
- Adds example plugin and documentation
=> Add example plugin

.coveragerc, clowder/clowder/cli/branch_controller.py, clowder/clowder/cli/checkout_controller.py, clowder/clowder/cli/clean_controller.py, clowder/clowder/cli/diff_controller.py, clowder/clowder/cli/parallel_commands.py, clowder/clowder/cli/prune_controller.py, clowder/clowder/cli/start_controller.py, clowder/clowder/cli/stash_controller.py, clowder/clowder/util/clowder_utils.py, clowder/clowder/yaml/loading.py, clowder/clowder/yaml/printing.py, clowder/clowder/yaml/validating.py, script/travis/after_script
- Uploads coverage.py results to s3 in addition to code climate coverage results
=> Upload coverage results to s3

.codeclimate.yml, clowder/clowder/git/project_repo.py, clowder/clowder/model/project.py
- Refactor to fix code climate issues
=> More refactoring

test/scripts/cats/checkout.sh, test/scripts/cats/diff.sh, test/scripts/cats/prune.sh, test/scripts/cats/reset.sh, test/scripts/cats/start.sh
- Add test cases to increase coverage of `-p`/`--projects` options
=> Increase test coverage

.circleci/config.yml, .travis.yml, README.md, clowder/clowder/cli/sync_controller.py, clowder/clowder/model/project.py, clowder/clowder/util/parallel_commands.py, clowder/requirements.txt, clowder_test/clowder_test/cli/base_controller.py, clowder_test/clowder_test/execute.py, script/clean, script/test, script/travis/after_script, script/travis/before_script, script/travis/install, test/scripts/cats/write_herd.sh, test/scripts/cats/write_prune.sh, test/scripts/cats/write_repo.sh, test/scripts/cats/write_start.sh, test/scripts/cocos2d/protocol.sh, test/scripts/cocos2d/write_protocol.sh, test/scripts/llvm/write_forks.sh, test/scripts/llvm/write_sync.sh, test/scripts/setup_local_test_directory.sh, test/scripts/swift/configure_remotes.sh, test/scripts/swift/write_configure_remotes.sh, test/scripts/test_utilities.sh
- Submits test coverage results to Codecov from Travis CI and Circle CI
=> Add test coverage for parallel tests and write tests on Circle CI 

.circleci/config.yml, appveyor.yml, clowder/requirements.txt, script/travis/install
- Adds code coverage to AppVeyor tests
=> Add test coverage to AppVeyor

src/clowder/git/repo.py, src/clowder/model/project.py
=> Fix clowder branch

.travis.yml, script/travis/before_script, src/clowder/error/clowder_yaml_error.py, src/clowder/model/fork.py, src/clowder/model/project.py, src/clowder/util/decorators.py, src/clowder/util/formatting.py, src/clowder/yaml/loading.py, src/clowder/yaml/parsing.py, src/clowder/yaml/validating.py, src/clowder/yaml/validation/sources.py, src/clowder/yaml/validation/util.py, test/scripts/cats/help.sh, test/scripts/cats/write_repo.sh, test/scripts/cats/yaml_validation.sh
=> Update test scripts for clowder.yaml validation

.circleci/config.yml, .gitignore, clowder_test/clowder_test/cli/base_controller.py, examples/README.md, examples/misc/README.md, examples/misc/clean.sh, examples/misc/init.sh, test/scripts/misc/forks.sh, test/scripts/misc/sources.sh, test/scripts/setup_local_test_directory.sh, test/scripts/test_example_misc.sh, test/scripts/test_utilities.sh
=> Add misc tests

README.md, clowder_test/clowder_test/clowder_test_app.py, clowder_test/setup.py, src/clowder/clowder_app.py, src/requirements.txt, src/setup.py
=> Remove argcomplete

.idea/inspectionProfiles/Project_Default.xml, src/clowder/clowder_repo.py, src/clowder/git/project_repo.py, src/clowder/git/project_repo_impl.py, src/clowder/git/repo.py, src/clowder/util/clowder_utils.py, src/clowder/util/formatting.py, src/clowder/util/parallel_commands.py
=> Use f strings

src/clowder/cli/save_controller.py, src/clowder/util/clowder_utils.py, test/scripts/cats/link.sh, test/scripts/cats/save.sh, test/scripts/cats/write_herd.sh, test/scripts/cats/write_prune.sh, test/scripts/cats/write_repo.sh, test/scripts/cats/write_start.sh, test/scripts/cats/yaml_validation.sh, test/unittests/test_clowder_repo.py
=> Update versions configuration for flat directory structure

src/clowder/error/clowder_yaml_error.py, src/clowder/model/fork.py, src/clowder/model/project.py, src/clowder/util/decorators.py, src/clowder/util/formatting.py, src/clowder/util/validation.py, test/scripts/cats/yaml_validation.sh
=> Add optional alias to projects

.travis.yml, CHANGELOG.md, CONTRIBUTING.md, README.md, src/clowder/git/project_repo_impl.py, src/clowder/git/project_repo_recursive.py, src/clowder/git/repo.py, src/setup.py, test/scripts/test_utilities.sh
Use GitPython instead of subprocess. Add Python 3.8 to Travis CI and setup.py
=> Refactor git commands and add Python 3.8

.circleci/config.yml, clowder_test/clowder_test/cli/base_controller.py, clowder_test/clowder_test/cli/llvm_controller.py, clowder_test/clowder_test/cli/misc_controller.py, clowder_test/clowder_test/clowder_test_app.py, src/clowder/model/fork.py, src/clowder/model/project.py, test/scripts/llvm/forks.sh, test/scripts/misc/forks.sh, test/scripts/misc/write_forks.sh, test/scripts/test_example_misc.sh, test/scripts/test_forall_script_env_fork.sh
=> Update fork handling

.github/workflows/main.yml, README.md
=> Add badge for GitHub Action workflow

examples/cats/clean.sh, src/clowder/model/project.py, test/scripts/cats/herd.sh
=> Infer path from project name if not specified

src/clowder/clowder.schema.json, src/clowder/model/defaults.py, test/scripts/cats/help.sh, test/scripts/cats/herd.sh
=> Make ref and remote defaults optional

.gitignore, examples/cats/clean.sh, src/clowder/model/project.py, src/clowder/util/formatting.py, src/clowder/util/yaml.py, test/scripts/cats/herd.sh
=> Update default project path to last name component

.gitignore, examples/misc/clean.sh, src/clowder/model/fork.py, src/clowder/model/project.py, test/scripts/misc/forks.sh, test/scripts/misc/sources.sh, test/scripts/misc/write_forks.sh
Forks were inheriting their source from the project instead of defaults, when not specified. Also adds fork name and last path component to project groups.
=> Fix a few fork bugs

.github/workflows/cancel.yml, .github/workflows/ci-cats-lfs.yml, clowder_test/clowder_test/cli/cats_controller.py, src/clowder/clowder.schema.json, src/clowder/git/repo.py, src/clowder/model/defaults.py, src/clowder/model/project.py, test/scripts/cats/lfs.sh, test/scripts/test_utilities.sh
=> Add git lfs support

src/clowder/git/project_repo.py, src/clowder/model/project.py, test/scripts/cats/git-config.sh, test/scripts/cats/groups.sh, test/scripts/misc/forks.sh, test/scripts/misc/sources.sh, test/scripts/misc/write_forks.sh
=> Add git herd alias to project git configs when running clowder herd command

src/clowder/cli/config.py, src/clowder/config/clowder_config.py, src/clowder/config/config.py, src/clowder/error.py, src/clowder/util/formatting.py, test/scripts/cats/config.sh
=> Make invalid config file a warning, unless running config commands

src/clowder/git/git_repo.py, src/clowder/git/project_repo_impl.py, src/clowder/git/project_repo_recursive.py
=> Print git output as stream

docs/clowder-repo.md, docs/commands.md, docs/examples/generate.sh, examples/cats/clowder-yaml-f.txt, examples/cats/clowder-yaml-r.txt, examples/cats/clowder-yaml.txt, src/clowder/cli/yaml.py, src/clowder/clowder_controller.py, src/clowder/config/config.py, test/scripts/cats/yaml.sh, test/scripts/test_utilities.sh
resolves #570 
Respect projects arguments for -r and no flags. Add --full/-f option to just print current file contents. Add tests for correct output in various scenarios.
=> Fix clowder yaml command

src/clowder/environment.py, src/clowder/util/formatting.py, test/scripts/cats/clowder-repo.sh
=> Fix handling of broken symlink

.circleci/config.yml, clowder_test/clowder_test/cli/misc_controller.py, examples/cats/clean.sh, examples/cats/init.sh, examples/misc/clean.sh, examples/misc/init.sh, examples/swift-projects/clean.sh, examples/swift-projects/init.sh, src/clowder/cli/config.py, src/clowder/cli/herd.py, src/clowder/model/source.py, test/scripts/cats/write_repo.sh, test/scripts/misc/forks.sh, test/scripts/misc/protocol.sh, test/scripts/misc/sources.sh, test/scripts/test_example_misc.sh, test/scripts/test_utilities.sh
=> Add protocol option to clowder herd

src/clowder/cli/config.py, test/scripts/cats/config.sh
=> Update clowder config set jobs command and add test

README.md, docs/clowder-yml-forks.md, docs/swift-clowder-yaml.md, docs/swift-update-checkout-config-json.md, examples/yaml-validation-description-test.clowder.yml, src/clowder/clowder_controller.py, src/clowder/model/source.py, src/clowder/util/clowder.schema.json
=> Convert sources from list to map

.codeclimate.yml, .idea/runConfigurations/clowder_debug___cats.xml, .idea/runConfigurations/clowder_init___cats.xml, README.md, clowder/util/file_system.py, clowder/util/formatting.py, clowder/util/yaml.py, docker-compose.yml, script/docker, script/process_readme.py, tests/functional/fixtures/cats_alternate_setups.py, tests/functional/fixtures/cats_init.py, tests/functional/fixtures/cats_init_herd.py, tests/functional/fixtures/misc_init.py, tests/functional/fixtures/misc_init_herd.py, tests/functional/given/file_system.py, tests/functional/given/mutating.py, tests/functional/then/file_system.py, tests/functional/util/clowder.py, tests/functional/util/connectivity.py, tests/functional/util/file_system.py
=> Make symlink relative

clowder/cli/yaml.py, clowder/data/model/clowder_base.py, clowder/data/model/defaults.py, clowder/data/model/group.py, clowder/data/model/project.py, clowder/data/model/upstream_defaults.py, clowder/util/yaml.py, tests/functional/data/yaml/command_output/clowder.yml, tests/functional/data/yaml/command_output/resolved.clowder.yml
=> Yaml output preserves order of dict keys

.gitattributes, CHANGELOG.md, Dockerfile, README.md, clowder/data/model/git_settings.py, clowder/data/resolved_git_settings.py, clowder/util/clowder.schema.json, docs/clowder-yml-syntax-reference.md, docs/resources/clowder.png, tests/functional/data/yaml/clowder.group.project/dict/git.submodules-defaults.clowder.yml, tests/functional/data/yaml/clowder.group.project/dict/git.submodules-project.clowder.yml, tests/functional/data/yaml/clowder.group.project/string/git.submodules-defaults.clowder.yml, tests/functional/data/yaml/clowder.group.projects.project/dict/git.submodules-defaults.clowder.yml, tests/functional/data/yaml/clowder.group.projects.project/dict/git.submodules-group.clowder.yml, tests/functional/data/yaml/clowder.group.projects.project/dict/git.submodules-project.clowder.yml, tests/functional/data/yaml/clowder.group.projects.project/string/git.submodules-defaults.clowder.yml, tests/functional/data/yaml/clowder.group.projects.project/string/git.submodules-group.clowder.yml, tests/functional/data/yaml/clowder.project/dict/git.submodules-defaults.clowder.yml, tests/functional/data/yaml/clowder.project/dict/git.submodules-project.clowder.yml, tests/functional/data/yaml/clowder.project/string/git.submodules-defaults.clowder.yml
=> Update submodules and docs
